### ISSUE TITLE
ocelot-ide.org is running the development build of React

### ISSUE THREAD

**Issue by lukenguyen145** [umass-compsci220/Ocelot#100]
I spotted this while using the "React Developer Tools" plugin. Is this something worth mentioning because I think the production build enhances the performance of the page?

**Comment by arjunguha** [comment]
Thanks. @sp1tz this may be worth fixing? I've only noticed performance problems with several dozen files -- but that is more likely due to bad programming pattern and not a debug/release issue.

**Comment by sp1tz** [comment]
https://github.com/umass-compsci220/Ocelot/blob/master/frontend/webpack.config.js#L6
https://webpack.js.org/guides/production/
