### ISSUE TITLE
Weird error message

### ISSUE THREAD

**Issue by emilyaherbert** [umass-compsci220/Ocelot#108]
This isn't valid JS, but it's a weird message to tell you that.

![image](https://user-images.githubusercontent.com/17410721/62079822-73511480-b21d-11e9-9ac5-a6fdec7646ab.png)

**Comment by arjunguha** [comment]
Wow. Thanks. It probably isn’t worth fixing in the short term. But, a more serious rework of EJS should fix this.

**Comment by arjunguha** [comment]
The way ElementaryJS is built, we don’t have a good handle on what errors are possible and when they can occur. I wonder if SweetJS can help. This is possibly a research topic.

**Comment by sp1tz** [comment]
@arjunguha can you please transfer this issue to EJS? I don't have access to do so.
