### ISSUE TITLE
Highlight matching braces and parens

### ISSUE THREAD

**Issue by arjunguha** [umass-compsci220/Ocelot#83]
Can we do this? It would help. I don't want paren autocomplete however.

**Comment by sp1tz** [comment]
>I don't want paren autocomplete however.

That often annoys me 😓

**Comment by arjunguha** [comment]
I can't tell if you're like or dislike paren-autocomplete.

However, Ocelot is not designed for you and me. E.g., it does not have "IntelliSense".
