### ISSUE TITLE
Ability to login with an access code

### ISSUE THREAD

**Issue by arjunguha** [umass-compsci220/Ocelot#94]
This is something that we will need over the summer: we will give students a set of access codes to login. after login, the system will behave exactly as it does right now. We cannot assume that all students will have access to a Google Account.

I suggest we build a new start panel that shows before the IDE, with three options:
	1. login with a google account
	2. login with an access code
	3. use without logging in

I think this will simplify the design of JumboContent, which has a lot of cruft to manage the transition between logging in and being logged out.

I suggest we create a CLI tool to manage access codes.

**Comment by sp1tz** [comment]
I think we can close this.
